// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: addgroup/proto/addgroup.proto

package addgroup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AddGroup_AddGroup_FullMethodName = "/YrcfAgent.AddGroup/AddGroup"
)

// AddGroupClient is the client API for AddGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddGroupClient interface {
	AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*AddGroupResponse, error)
}

type addGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewAddGroupClient(cc grpc.ClientConnInterface) AddGroupClient {
	return &addGroupClient{cc}
}

func (c *addGroupClient) AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*AddGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGroupResponse)
	err := c.cc.Invoke(ctx, AddGroup_AddGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddGroupServer is the server API for AddGroup service.
// All implementations must embed UnimplementedAddGroupServer
// for forward compatibility
type AddGroupServer interface {
	AddGroup(context.Context, *AddGroupRequest) (*AddGroupResponse, error)
	mustEmbedUnimplementedAddGroupServer()
}

// UnimplementedAddGroupServer must be embedded to have forward compatible implementations.
type UnimplementedAddGroupServer struct {
}

func (UnimplementedAddGroupServer) AddGroup(context.Context, *AddGroupRequest) (*AddGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroup not implemented")
}
func (UnimplementedAddGroupServer) mustEmbedUnimplementedAddGroupServer() {}

// UnsafeAddGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddGroupServer will
// result in compilation errors.
type UnsafeAddGroupServer interface {
	mustEmbedUnimplementedAddGroupServer()
}

func RegisterAddGroupServer(s grpc.ServiceRegistrar, srv AddGroupServer) {
	s.RegisterService(&AddGroup_ServiceDesc, srv)
}

func _AddGroup_AddGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddGroupServer).AddGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddGroup_AddGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddGroupServer).AddGroup(ctx, req.(*AddGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddGroup_ServiceDesc is the grpc.ServiceDesc for AddGroup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddGroup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "YrcfAgent.AddGroup",
	HandlerType: (*AddGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGroup",
			Handler:    _AddGroup_AddGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addgroup/proto/addgroup.proto",
}
