// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: bucket/proto/bucket.proto

package bucket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	proto "yrcf_grpc_case/grpc/common/proto"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BucketConfig_Protocol int32

const (
	BucketConfig_HTTPS BucketConfig_Protocol = 0
	BucketConfig_HTTP  BucketConfig_Protocol = 1
)

// Enum value maps for BucketConfig_Protocol.
var (
	BucketConfig_Protocol_name = map[int32]string{
		0: "HTTPS",
		1: "HTTP",
	}
	BucketConfig_Protocol_value = map[string]int32{
		"HTTPS": 0,
		"HTTP":  1,
	}
)

func (x BucketConfig_Protocol) Enum() *BucketConfig_Protocol {
	p := new(BucketConfig_Protocol)
	*p = x
	return p
}

func (x BucketConfig_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BucketConfig_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_bucket_proto_bucket_proto_enumTypes[0].Descriptor()
}

func (BucketConfig_Protocol) Type() protoreflect.EnumType {
	return &file_bucket_proto_bucket_proto_enumTypes[0]
}

func (x BucketConfig_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BucketConfig_Protocol.Descriptor instead.
func (BucketConfig_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{0, 0}
}

type BucketConfig_UriStyle int32

const (
	BucketConfig_PATH         BucketConfig_UriStyle = 0
	BucketConfig_VIRTUAL_HOST BucketConfig_UriStyle = 1
)

// Enum value maps for BucketConfig_UriStyle.
var (
	BucketConfig_UriStyle_name = map[int32]string{
		0: "PATH",
		1: "VIRTUAL_HOST",
	}
	BucketConfig_UriStyle_value = map[string]int32{
		"PATH":         0,
		"VIRTUAL_HOST": 1,
	}
)

func (x BucketConfig_UriStyle) Enum() *BucketConfig_UriStyle {
	p := new(BucketConfig_UriStyle)
	*p = x
	return p
}

func (x BucketConfig_UriStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BucketConfig_UriStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_bucket_proto_bucket_proto_enumTypes[1].Descriptor()
}

func (BucketConfig_UriStyle) Type() protoreflect.EnumType {
	return &file_bucket_proto_bucket_proto_enumTypes[1]
}

func (x BucketConfig_UriStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BucketConfig_UriStyle.Descriptor instead.
func (BucketConfig_UriStyle) EnumDescriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{0, 1}
}

type BucketConfig_LibraryType int32

const (
	BucketConfig_LIBS3 BucketConfig_LibraryType = 0
	BucketConfig_AWS   BucketConfig_LibraryType = 1
)

// Enum value maps for BucketConfig_LibraryType.
var (
	BucketConfig_LibraryType_name = map[int32]string{
		0: "LIBS3",
		1: "AWS",
	}
	BucketConfig_LibraryType_value = map[string]int32{
		"LIBS3": 0,
		"AWS":   1,
	}
)

func (x BucketConfig_LibraryType) Enum() *BucketConfig_LibraryType {
	p := new(BucketConfig_LibraryType)
	*p = x
	return p
}

func (x BucketConfig_LibraryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BucketConfig_LibraryType) Descriptor() protoreflect.EnumDescriptor {
	return file_bucket_proto_bucket_proto_enumTypes[2].Descriptor()
}

func (BucketConfig_LibraryType) Type() protoreflect.EnumType {
	return &file_bucket_proto_bucket_proto_enumTypes[2]
}

func (x BucketConfig_LibraryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BucketConfig_LibraryType.Descriptor instead.
func (BucketConfig_LibraryType) EnumDescriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{0, 2}
}

type AddOrTestBucketRequest_Operation int32

const (
	AddOrTestBucketRequest_ADD_BUCKET  AddOrTestBucketRequest_Operation = 0
	AddOrTestBucketRequest_TEST_BUCKET AddOrTestBucketRequest_Operation = 1
)

// Enum value maps for AddOrTestBucketRequest_Operation.
var (
	AddOrTestBucketRequest_Operation_name = map[int32]string{
		0: "ADD_BUCKET",
		1: "TEST_BUCKET",
	}
	AddOrTestBucketRequest_Operation_value = map[string]int32{
		"ADD_BUCKET":  0,
		"TEST_BUCKET": 1,
	}
)

func (x AddOrTestBucketRequest_Operation) Enum() *AddOrTestBucketRequest_Operation {
	p := new(AddOrTestBucketRequest_Operation)
	*p = x
	return p
}

func (x AddOrTestBucketRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddOrTestBucketRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_bucket_proto_bucket_proto_enumTypes[3].Descriptor()
}

func (AddOrTestBucketRequest_Operation) Type() protoreflect.EnumType {
	return &file_bucket_proto_bucket_proto_enumTypes[3]
}

func (x AddOrTestBucketRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddOrTestBucketRequest_Operation.Descriptor instead.
func (AddOrTestBucketRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{7, 0}
}

type BucketConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostName        string                   `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	BucketName      string                   `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Protocol        BucketConfig_Protocol    `protobuf:"varint,3,opt,name=protocol,proto3,enum=YrcfAgent.BucketConfig_Protocol" json:"protocol,omitempty"`
	UriStyle        BucketConfig_UriStyle    `protobuf:"varint,4,opt,name=uri_style,json=uriStyle,proto3,enum=YrcfAgent.BucketConfig_UriStyle" json:"uri_style,omitempty"`
	Region          string                   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	AccessKey       string                   `protobuf:"bytes,6,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretAccessKey string                   `protobuf:"bytes,7,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	LibType         BucketConfig_LibraryType `protobuf:"varint,8,opt,name=lib_type,json=libType,proto3,enum=YrcfAgent.BucketConfig_LibraryType" json:"lib_type,omitempty"`
	Token           string                   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *BucketConfig) Reset() {
	*x = BucketConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketConfig) ProtoMessage() {}

func (x *BucketConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketConfig.ProtoReflect.Descriptor instead.
func (*BucketConfig) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{0}
}

func (x *BucketConfig) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *BucketConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *BucketConfig) GetProtocol() BucketConfig_Protocol {
	if x != nil {
		return x.Protocol
	}
	return BucketConfig_HTTPS
}

func (x *BucketConfig) GetUriStyle() BucketConfig_UriStyle {
	if x != nil {
		return x.UriStyle
	}
	return BucketConfig_PATH
}

func (x *BucketConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *BucketConfig) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *BucketConfig) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *BucketConfig) GetLibType() BucketConfig_LibraryType {
	if x != nil {
		return x.LibType
	}
	return BucketConfig_LIBS3
}

func (x *BucketConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type BucketInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketId     uint32        `protobuf:"varint,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	BucketConfig *BucketConfig `protobuf:"bytes,2,opt,name=bucket_config,json=bucketConfig,proto3" json:"bucket_config,omitempty"`
}

func (x *BucketInfo) Reset() {
	*x = BucketInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketInfo) ProtoMessage() {}

func (x *BucketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketInfo.ProtoReflect.Descriptor instead.
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{1}
}

func (x *BucketInfo) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

func (x *BucketInfo) GetBucketConfig() *BucketConfig {
	if x != nil {
		return x.BucketConfig
	}
	return nil
}

// message for list bucket
type ListBucketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{2}
}

type ListBucketsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	BucketInfo []*BucketInfo `protobuf:"bytes,2,rep,name=bucket_info,json=bucketInfo,proto3" json:"bucket_info,omitempty"`
}

func (x *ListBucketsResponse) Reset() {
	*x = ListBucketsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse) ProtoMessage() {}

func (x *ListBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{3}
}

func (x *ListBucketsResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListBucketsResponse) GetBucketInfo() []*BucketInfo {
	if x != nil {
		return x.BucketInfo
	}
	return nil
}

type BucketState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketId   uint32   `protobuf:"varint,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	DownNodeIp []string `protobuf:"bytes,2,rep,name=down_node_ip,json=downNodeIp,proto3" json:"down_node_ip,omitempty"`
}

func (x *BucketState) Reset() {
	*x = BucketState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketState) ProtoMessage() {}

func (x *BucketState) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketState.ProtoReflect.Descriptor instead.
func (*BucketState) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{4}
}

func (x *BucketState) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

func (x *BucketState) GetDownNodeIp() []string {
	if x != nil {
		return x.DownNodeIp
	}
	return nil
}

// message for list bucket state
type ListBucketStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketId uint32 `protobuf:"varint,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
}

func (x *ListBucketStateRequest) Reset() {
	*x = ListBucketStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketStateRequest) ProtoMessage() {}

func (x *ListBucketStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketStateRequest.ProtoReflect.Descriptor instead.
func (*ListBucketStateRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{5}
}

func (x *ListBucketStateRequest) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

type ListBucketStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      *proto.ResMes  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	BucketState []*BucketState `protobuf:"bytes,2,rep,name=bucket_state,json=bucketState,proto3" json:"bucket_state,omitempty"`
}

func (x *ListBucketStateResponse) Reset() {
	*x = ListBucketStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketStateResponse) ProtoMessage() {}

func (x *ListBucketStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketStateResponse.ProtoReflect.Descriptor instead.
func (*ListBucketStateResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{6}
}

func (x *ListBucketStateResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListBucketStateResponse) GetBucketState() []*BucketState {
	if x != nil {
		return x.BucketState
	}
	return nil
}

// message for add and test bucket
type AddOrTestBucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op             AddOrTestBucketRequest_Operation `protobuf:"varint,1,opt,name=op,proto3,enum=YrcfAgent.AddOrTestBucketRequest_Operation" json:"op,omitempty"`
	BucketConfig   *BucketConfig                    `protobuf:"bytes,2,opt,name=bucket_config,json=bucketConfig,proto3" json:"bucket_config,omitempty"`
	AddWithoutTest bool                             `protobuf:"varint,3,opt,name=add_without_test,json=addWithoutTest,proto3" json:"add_without_test,omitempty"`
}

func (x *AddOrTestBucketRequest) Reset() {
	*x = AddOrTestBucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrTestBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrTestBucketRequest) ProtoMessage() {}

func (x *AddOrTestBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrTestBucketRequest.ProtoReflect.Descriptor instead.
func (*AddOrTestBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{7}
}

func (x *AddOrTestBucketRequest) GetOp() AddOrTestBucketRequest_Operation {
	if x != nil {
		return x.Op
	}
	return AddOrTestBucketRequest_ADD_BUCKET
}

func (x *AddOrTestBucketRequest) GetBucketConfig() *BucketConfig {
	if x != nil {
		return x.BucketConfig
	}
	return nil
}

func (x *AddOrTestBucketRequest) GetAddWithoutTest() bool {
	if x != nil {
		return x.AddWithoutTest
	}
	return false
}

type AddOrTestBucketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddOrTestBucketResponse) Reset() {
	*x = AddOrTestBucketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrTestBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrTestBucketResponse) ProtoMessage() {}

func (x *AddOrTestBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrTestBucketResponse.ProtoReflect.Descriptor instead.
func (*AddOrTestBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{8}
}

func (x *AddOrTestBucketResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

// message for bucket update
type UpdateBucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketId        uint32 `protobuf:"varint,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	AccessKey       string `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretAccessKey string `protobuf:"bytes,3,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
}

func (x *UpdateBucketRequest) Reset() {
	*x = UpdateBucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBucketRequest) ProtoMessage() {}

func (x *UpdateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBucketRequest.ProtoReflect.Descriptor instead.
func (*UpdateBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBucketRequest) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

func (x *UpdateBucketRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *UpdateBucketRequest) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

type UpdateBucketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UpdateBucketResponse) Reset() {
	*x = UpdateBucketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBucketResponse) ProtoMessage() {}

func (x *UpdateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBucketResponse.ProtoReflect.Descriptor instead.
func (*UpdateBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBucketResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

// message for bucket delete
type DeleteBucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketId uint32 `protobuf:"varint,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBucketRequest) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

type DeleteBucketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteBucketResponse) Reset() {
	*x = DeleteBucketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_proto_bucket_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketResponse) ProtoMessage() {}

func (x *DeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_proto_bucket_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_proto_bucket_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBucketResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_bucket_proto_bucket_proto protoreflect.FileDescriptor

var file_bucket_proto_bucket_proto_rawDesc = []byte{
	0x0a, 0x19, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x59, 0x72, 0x63,
	0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x03, 0x0a, 0x0c, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x3d, 0x0a, 0x09, 0x75, 0x72, 0x69, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x55, 0x72, 0x69, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x08, 0x75, 0x72, 0x69, 0x53, 0x74, 0x79,
	0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x3e, 0x0a, 0x08, 0x6c, 0x69, 0x62, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6c, 0x69,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1f, 0x0a, 0x08, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x53,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x01, 0x22, 0x26, 0x0a, 0x08,
	0x55, 0x72, 0x69, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x54, 0x48,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x5f, 0x48, 0x4f,
	0x53, 0x54, 0x10, 0x01, 0x22, 0x21, 0x0a, 0x0b, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49, 0x42, 0x53, 0x33, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x41, 0x57, 0x53, 0x10, 0x01, 0x22, 0x67, 0x0a, 0x0a, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0d, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x59, 0x72, 0x63, 0x66,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x0c, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6e, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x36,
	0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4c, 0x0a, 0x0b, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x70, 0x22, 0x35, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0xeb, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x54, 0x65, 0x73, 0x74,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a,
	0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x59, 0x72, 0x63, 0x66,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0c, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x5f,
	0x77, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x54, 0x65,
	0x73, 0x74, 0x22, 0x2c, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x0a, 0x41, 0x44, 0x44, 0x5f, 0x42, 0x55, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x54, 0x45, 0x53, 0x54, 0x5f, 0x42, 0x55, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x01,
	0x22, 0x3a, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65,
	0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7d, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12,
	0x2a, 0x0a, 0x11, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x14, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x32, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0xac, 0x03, 0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x4c, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x59, 0x72,
	0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x59, 0x72, 0x63,
	0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e,
	0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x54, 0x65, 0x73,
	0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x59, 0x72, 0x63,
	0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x54, 0x65, 0x73, 0x74,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f,
	0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1e,
	0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4f, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x1e, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x2a, 0x5a, 0x28, 0x79, 0x72, 0x63, 0x66, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61,
	0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x3b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bucket_proto_bucket_proto_rawDescOnce sync.Once
	file_bucket_proto_bucket_proto_rawDescData = file_bucket_proto_bucket_proto_rawDesc
)

func file_bucket_proto_bucket_proto_rawDescGZIP() []byte {
	file_bucket_proto_bucket_proto_rawDescOnce.Do(func() {
		file_bucket_proto_bucket_proto_rawDescData = protoimpl.X.CompressGZIP(file_bucket_proto_bucket_proto_rawDescData)
	})
	return file_bucket_proto_bucket_proto_rawDescData
}

var file_bucket_proto_bucket_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_bucket_proto_bucket_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bucket_proto_bucket_proto_goTypes = []any{
	(BucketConfig_Protocol)(0),            // 0: YrcfAgent.BucketConfig.Protocol
	(BucketConfig_UriStyle)(0),            // 1: YrcfAgent.BucketConfig.UriStyle
	(BucketConfig_LibraryType)(0),         // 2: YrcfAgent.BucketConfig.LibraryType
	(AddOrTestBucketRequest_Operation)(0), // 3: YrcfAgent.AddOrTestBucketRequest.Operation
	(*BucketConfig)(nil),                  // 4: YrcfAgent.BucketConfig
	(*BucketInfo)(nil),                    // 5: YrcfAgent.BucketInfo
	(*ListBucketsRequest)(nil),            // 6: YrcfAgent.ListBucketsRequest
	(*ListBucketsResponse)(nil),           // 7: YrcfAgent.ListBucketsResponse
	(*BucketState)(nil),                   // 8: YrcfAgent.BucketState
	(*ListBucketStateRequest)(nil),        // 9: YrcfAgent.ListBucketStateRequest
	(*ListBucketStateResponse)(nil),       // 10: YrcfAgent.ListBucketStateResponse
	(*AddOrTestBucketRequest)(nil),        // 11: YrcfAgent.AddOrTestBucketRequest
	(*AddOrTestBucketResponse)(nil),       // 12: YrcfAgent.AddOrTestBucketResponse
	(*UpdateBucketRequest)(nil),           // 13: YrcfAgent.UpdateBucketRequest
	(*UpdateBucketResponse)(nil),          // 14: YrcfAgent.UpdateBucketResponse
	(*DeleteBucketRequest)(nil),           // 15: YrcfAgent.DeleteBucketRequest
	(*DeleteBucketResponse)(nil),          // 16: YrcfAgent.DeleteBucketResponse
	(*proto.ResMes)(nil),                  // 17: ResMes
}
var file_bucket_proto_bucket_proto_depIdxs = []int32{
	0,  // 0: YrcfAgent.BucketConfig.protocol:type_name -> YrcfAgent.BucketConfig.Protocol
	1,  // 1: YrcfAgent.BucketConfig.uri_style:type_name -> YrcfAgent.BucketConfig.UriStyle
	2,  // 2: YrcfAgent.BucketConfig.lib_type:type_name -> YrcfAgent.BucketConfig.LibraryType
	4,  // 3: YrcfAgent.BucketInfo.bucket_config:type_name -> YrcfAgent.BucketConfig
	17, // 4: YrcfAgent.ListBucketsResponse.result:type_name -> ResMes
	5,  // 5: YrcfAgent.ListBucketsResponse.bucket_info:type_name -> YrcfAgent.BucketInfo
	17, // 6: YrcfAgent.ListBucketStateResponse.result:type_name -> ResMes
	8,  // 7: YrcfAgent.ListBucketStateResponse.bucket_state:type_name -> YrcfAgent.BucketState
	3,  // 8: YrcfAgent.AddOrTestBucketRequest.op:type_name -> YrcfAgent.AddOrTestBucketRequest.Operation
	4,  // 9: YrcfAgent.AddOrTestBucketRequest.bucket_config:type_name -> YrcfAgent.BucketConfig
	17, // 10: YrcfAgent.AddOrTestBucketResponse.result:type_name -> ResMes
	17, // 11: YrcfAgent.UpdateBucketResponse.result:type_name -> ResMes
	17, // 12: YrcfAgent.DeleteBucketResponse.result:type_name -> ResMes
	6,  // 13: YrcfAgent.Bucket.ListBuckets:input_type -> YrcfAgent.ListBucketsRequest
	9,  // 14: YrcfAgent.Bucket.ListBucketState:input_type -> YrcfAgent.ListBucketStateRequest
	11, // 15: YrcfAgent.Bucket.AddOrTestBucket:input_type -> YrcfAgent.AddOrTestBucketRequest
	13, // 16: YrcfAgent.Bucket.UpdateBucket:input_type -> YrcfAgent.UpdateBucketRequest
	15, // 17: YrcfAgent.Bucket.DeleteBucket:input_type -> YrcfAgent.DeleteBucketRequest
	7,  // 18: YrcfAgent.Bucket.ListBuckets:output_type -> YrcfAgent.ListBucketsResponse
	10, // 19: YrcfAgent.Bucket.ListBucketState:output_type -> YrcfAgent.ListBucketStateResponse
	12, // 20: YrcfAgent.Bucket.AddOrTestBucket:output_type -> YrcfAgent.AddOrTestBucketResponse
	14, // 21: YrcfAgent.Bucket.UpdateBucket:output_type -> YrcfAgent.UpdateBucketResponse
	16, // 22: YrcfAgent.Bucket.DeleteBucket:output_type -> YrcfAgent.DeleteBucketResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_bucket_proto_bucket_proto_init() }
func file_bucket_proto_bucket_proto_init() {
	if File_bucket_proto_bucket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bucket_proto_bucket_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BucketConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BucketInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListBucketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListBucketsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BucketState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListBucketStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListBucketStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AddOrTestBucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AddOrTestBucketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBucketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_proto_bucket_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBucketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bucket_proto_bucket_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bucket_proto_bucket_proto_goTypes,
		DependencyIndexes: file_bucket_proto_bucket_proto_depIdxs,
		EnumInfos:         file_bucket_proto_bucket_proto_enumTypes,
		MessageInfos:      file_bucket_proto_bucket_proto_msgTypes,
	}.Build()
	File_bucket_proto_bucket_proto = out.File
	file_bucket_proto_bucket_proto_rawDesc = nil
	file_bucket_proto_bucket_proto_goTypes = nil
	file_bucket_proto_bucket_proto_depIdxs = nil
}
