// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: qos/proto/qos.proto

package qos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	proto "yrcf_grpc_case/grpc/common/proto/"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// add qos
type AddQosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rbps  uint64 `protobuf:"varint,1,opt,name=rbps,proto3" json:"rbps,omitempty"`
	Wbps  uint64 `protobuf:"varint,2,opt,name=wbps,proto3" json:"wbps,omitempty"`
	Riops uint64 `protobuf:"varint,3,opt,name=riops,proto3" json:"riops,omitempty"`
	Wiops uint64 `protobuf:"varint,4,opt,name=wiops,proto3" json:"wiops,omitempty"`
	Tbps  uint64 `protobuf:"varint,5,opt,name=tbps,proto3" json:"tbps,omitempty"`
	Tiops uint64 `protobuf:"varint,6,opt,name=tiops,proto3" json:"tiops,omitempty"`
	Mops  uint64 `protobuf:"varint,7,opt,name=mops,proto3" json:"mops,omitempty"`
	Path  string `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *AddQosRequest) Reset() {
	*x = AddQosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_proto_qos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQosRequest) ProtoMessage() {}

func (x *AddQosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qos_proto_qos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQosRequest.ProtoReflect.Descriptor instead.
func (*AddQosRequest) Descriptor() ([]byte, []int) {
	return file_qos_proto_qos_proto_rawDescGZIP(), []int{0}
}

func (x *AddQosRequest) GetRbps() uint64 {
	if x != nil {
		return x.Rbps
	}
	return 0
}

func (x *AddQosRequest) GetWbps() uint64 {
	if x != nil {
		return x.Wbps
	}
	return 0
}

func (x *AddQosRequest) GetRiops() uint64 {
	if x != nil {
		return x.Riops
	}
	return 0
}

func (x *AddQosRequest) GetWiops() uint64 {
	if x != nil {
		return x.Wiops
	}
	return 0
}

func (x *AddQosRequest) GetTbps() uint64 {
	if x != nil {
		return x.Tbps
	}
	return 0
}

func (x *AddQosRequest) GetTiops() uint64 {
	if x != nil {
		return x.Tiops
	}
	return 0
}

func (x *AddQosRequest) GetMops() uint64 {
	if x != nil {
		return x.Mops
	}
	return 0
}

func (x *AddQosRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AddQosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddQosResponse) Reset() {
	*x = AddQosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_proto_qos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQosResponse) ProtoMessage() {}

func (x *AddQosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qos_proto_qos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQosResponse.ProtoReflect.Descriptor instead.
func (*AddQosResponse) Descriptor() ([]byte, []int) {
	return file_qos_proto_qos_proto_rawDescGZIP(), []int{1}
}

func (x *AddQosResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

// list qos
type ListQosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Prefix bool   `protobuf:"varint,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *ListQosRequest) Reset() {
	*x = ListQosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_proto_qos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQosRequest) ProtoMessage() {}

func (x *ListQosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qos_proto_qos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQosRequest.ProtoReflect.Descriptor instead.
func (*ListQosRequest) Descriptor() ([]byte, []int) {
	return file_qos_proto_qos_proto_rawDescGZIP(), []int{2}
}

func (x *ListQosRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListQosRequest) GetPrefix() bool {
	if x != nil {
		return x.Prefix
	}
	return false
}

type QosInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eid   string `protobuf:"bytes,1,opt,name=eid,proto3" json:"eid,omitempty"`
	Rbps  uint64 `protobuf:"varint,2,opt,name=rbps,proto3" json:"rbps,omitempty"`
	Wbps  uint64 `protobuf:"varint,3,opt,name=wbps,proto3" json:"wbps,omitempty"`
	Riops uint64 `protobuf:"varint,4,opt,name=riops,proto3" json:"riops,omitempty"`
	Wiops uint64 `protobuf:"varint,5,opt,name=wiops,proto3" json:"wiops,omitempty"`
	Tbps  uint64 `protobuf:"varint,6,opt,name=tbps,proto3" json:"tbps,omitempty"`
	Tiops uint64 `protobuf:"varint,7,opt,name=tiops,proto3" json:"tiops,omitempty"`
	Mops  uint64 `protobuf:"varint,8,opt,name=mops,proto3" json:"mops,omitempty"`
	Path  string `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *QosInfo) Reset() {
	*x = QosInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_proto_qos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QosInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosInfo) ProtoMessage() {}

func (x *QosInfo) ProtoReflect() protoreflect.Message {
	mi := &file_qos_proto_qos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosInfo.ProtoReflect.Descriptor instead.
func (*QosInfo) Descriptor() ([]byte, []int) {
	return file_qos_proto_qos_proto_rawDescGZIP(), []int{3}
}

func (x *QosInfo) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

func (x *QosInfo) GetRbps() uint64 {
	if x != nil {
		return x.Rbps
	}
	return 0
}

func (x *QosInfo) GetWbps() uint64 {
	if x != nil {
		return x.Wbps
	}
	return 0
}

func (x *QosInfo) GetRiops() uint64 {
	if x != nil {
		return x.Riops
	}
	return 0
}

func (x *QosInfo) GetWiops() uint64 {
	if x != nil {
		return x.Wiops
	}
	return 0
}

func (x *QosInfo) GetTbps() uint64 {
	if x != nil {
		return x.Tbps
	}
	return 0
}

func (x *QosInfo) GetTiops() uint64 {
	if x != nil {
		return x.Tiops
	}
	return 0
}

func (x *QosInfo) GetMops() uint64 {
	if x != nil {
		return x.Mops
	}
	return 0
}

func (x *QosInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListQosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	QosInfoList []*QosInfo    `protobuf:"bytes,2,rep,name=qos_info_list,json=qosInfoList,proto3" json:"qos_info_list,omitempty"`
}

func (x *ListQosResponse) Reset() {
	*x = ListQosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_proto_qos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQosResponse) ProtoMessage() {}

func (x *ListQosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qos_proto_qos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQosResponse.ProtoReflect.Descriptor instead.
func (*ListQosResponse) Descriptor() ([]byte, []int) {
	return file_qos_proto_qos_proto_rawDescGZIP(), []int{4}
}

func (x *ListQosResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListQosResponse) GetQosInfoList() []*QosInfo {
	if x != nil {
		return x.QosInfoList
	}
	return nil
}

// delete qos
type DeleteQosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive bool   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Force     bool   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *DeleteQosRequest) Reset() {
	*x = DeleteQosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_proto_qos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQosRequest) ProtoMessage() {}

func (x *DeleteQosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qos_proto_qos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQosRequest.ProtoReflect.Descriptor instead.
func (*DeleteQosRequest) Descriptor() ([]byte, []int) {
	return file_qos_proto_qos_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteQosRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteQosRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *DeleteQosRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteQosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteQosResponse) Reset() {
	*x = DeleteQosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_proto_qos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQosResponse) ProtoMessage() {}

func (x *DeleteQosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qos_proto_qos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQosResponse.ProtoReflect.Descriptor instead.
func (*DeleteQosResponse) Descriptor() ([]byte, []int) {
	return file_qos_proto_qos_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteQosResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_qos_proto_qos_proto protoreflect.FileDescriptor

var file_qos_proto_qos_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x1a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb5, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x62, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x72, 0x62, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x62, 0x70, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x77, 0x62, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69,
	0x6f, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x69, 0x6f, 0x70, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x6f, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x77, 0x69, 0x6f, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x62, 0x70, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x62, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x6f, 0x70, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x69, 0x6f, 0x70, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x70, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x6d, 0x6f, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3b, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x51,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x59, 0x72, 0x63,
	0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3c, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x22, 0xc1, 0x01, 0x0a, 0x07, 0x51, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x62, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x72, 0x62, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x62, 0x70, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x77, 0x62, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x6f,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x69, 0x6f, 0x70, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x69, 0x6f, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x77, 0x69, 0x6f, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x62, 0x70, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x62, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6f,
	0x70, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x69, 0x6f, 0x70, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x70, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6d,
	0x6f, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x74, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x51,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x59, 0x72, 0x63,
	0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x71, 0x6f, 0x73, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x59,
	0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x51, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0b, 0x71, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5a, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69,
	0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73,
	0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x3e, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65,
	0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xd4, 0x01, 0x0a, 0x03, 0x51, 0x6f,
	0x73, 0x12, 0x3f, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x51, 0x6f, 0x73, 0x12, 0x18, 0x2e, 0x59, 0x72,
	0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x51, 0x6f, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x6f, 0x73, 0x12,
	0x1b, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x59,
	0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07,
	0x4c, 0x69, 0x73, 0x74, 0x51, 0x6f, 0x73, 0x12, 0x19, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x24, 0x5a, 0x22, 0x79, 0x72, 0x63, 0x66, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61,
	0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x71, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x3b, 0x71, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qos_proto_qos_proto_rawDescOnce sync.Once
	file_qos_proto_qos_proto_rawDescData = file_qos_proto_qos_proto_rawDesc
)

func file_qos_proto_qos_proto_rawDescGZIP() []byte {
	file_qos_proto_qos_proto_rawDescOnce.Do(func() {
		file_qos_proto_qos_proto_rawDescData = protoimpl.X.CompressGZIP(file_qos_proto_qos_proto_rawDescData)
	})
	return file_qos_proto_qos_proto_rawDescData
}

var file_qos_proto_qos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_qos_proto_qos_proto_goTypes = []any{
	(*AddQosRequest)(nil),     // 0: YrcfAgent.AddQosRequest
	(*AddQosResponse)(nil),    // 1: YrcfAgent.AddQosResponse
	(*ListQosRequest)(nil),    // 2: YrcfAgent.ListQosRequest
	(*QosInfo)(nil),           // 3: YrcfAgent.QosInfo
	(*ListQosResponse)(nil),   // 4: YrcfAgent.ListQosResponse
	(*DeleteQosRequest)(nil),  // 5: YrcfAgent.DeleteQosRequest
	(*DeleteQosResponse)(nil), // 6: YrcfAgent.DeleteQosResponse
	(*proto.ResMes)(nil),      // 7: YrcfAgent.ResMes
}
var file_qos_proto_qos_proto_depIdxs = []int32{
	7, // 0: YrcfAgent.AddQosResponse.result:type_name -> YrcfAgent.ResMes
	7, // 1: YrcfAgent.ListQosResponse.result:type_name -> YrcfAgent.ResMes
	3, // 2: YrcfAgent.ListQosResponse.qos_info_list:type_name -> YrcfAgent.QosInfo
	7, // 3: YrcfAgent.DeleteQosResponse.result:type_name -> YrcfAgent.ResMes
	0, // 4: YrcfAgent.Qos.AddQos:input_type -> YrcfAgent.AddQosRequest
	5, // 5: YrcfAgent.Qos.DeleteQos:input_type -> YrcfAgent.DeleteQosRequest
	2, // 6: YrcfAgent.Qos.ListQos:input_type -> YrcfAgent.ListQosRequest
	1, // 7: YrcfAgent.Qos.AddQos:output_type -> YrcfAgent.AddQosResponse
	6, // 8: YrcfAgent.Qos.DeleteQos:output_type -> YrcfAgent.DeleteQosResponse
	4, // 9: YrcfAgent.Qos.ListQos:output_type -> YrcfAgent.ListQosResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_qos_proto_qos_proto_init() }
func file_qos_proto_qos_proto_init() {
	if File_qos_proto_qos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qos_proto_qos_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddQosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qos_proto_qos_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddQosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qos_proto_qos_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListQosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qos_proto_qos_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*QosInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qos_proto_qos_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListQosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qos_proto_qos_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteQosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qos_proto_qos_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteQosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qos_proto_qos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qos_proto_qos_proto_goTypes,
		DependencyIndexes: file_qos_proto_qos_proto_depIdxs,
		MessageInfos:      file_qos_proto_qos_proto_msgTypes,
	}.Build()
	File_qos_proto_qos_proto = out.File
	file_qos_proto_qos_proto_rawDesc = nil
	file_qos_proto_qos_proto_goTypes = nil
	file_qos_proto_qos_proto_depIdxs = nil
}
