// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: ossoverview/proto/ossoverview.proto

package ossoverview

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	OssOverview_OssOverview_FullMethodName = "/YrcfAgent.OssOverview/OssOverview"
)

// OssOverviewClient is the client API for OssOverview service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OssOverviewClient interface {
	OssOverview(ctx context.Context, in *OssOverviewRequest, opts ...grpc.CallOption) (*OssOverviewResponse, error)
}

type ossOverviewClient struct {
	cc grpc.ClientConnInterface
}

func NewOssOverviewClient(cc grpc.ClientConnInterface) OssOverviewClient {
	return &ossOverviewClient{cc}
}

func (c *ossOverviewClient) OssOverview(ctx context.Context, in *OssOverviewRequest, opts ...grpc.CallOption) (*OssOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OssOverviewResponse)
	err := c.cc.Invoke(ctx, OssOverview_OssOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OssOverviewServer is the server API for OssOverview service.
// All implementations must embed UnimplementedOssOverviewServer
// for forward compatibility
type OssOverviewServer interface {
	OssOverview(context.Context, *OssOverviewRequest) (*OssOverviewResponse, error)
	mustEmbedUnimplementedOssOverviewServer()
}

// UnimplementedOssOverviewServer must be embedded to have forward compatible implementations.
type UnimplementedOssOverviewServer struct {
}

func (UnimplementedOssOverviewServer) OssOverview(context.Context, *OssOverviewRequest) (*OssOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OssOverview not implemented")
}
func (UnimplementedOssOverviewServer) mustEmbedUnimplementedOssOverviewServer() {}

// UnsafeOssOverviewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OssOverviewServer will
// result in compilation errors.
type UnsafeOssOverviewServer interface {
	mustEmbedUnimplementedOssOverviewServer()
}

func RegisterOssOverviewServer(s grpc.ServiceRegistrar, srv OssOverviewServer) {
	s.RegisterService(&OssOverview_ServiceDesc, srv)
}

func _OssOverview_OssOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OssOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssOverviewServer).OssOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OssOverview_OssOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssOverviewServer).OssOverview(ctx, req.(*OssOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OssOverview_ServiceDesc is the grpc.ServiceDesc for OssOverview service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OssOverview_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "YrcfAgent.OssOverview",
	HandlerType: (*OssOverviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OssOverview",
			Handler:    _OssOverview_OssOverview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ossoverview/proto/ossoverview.proto",
}
