// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: rmdir/proto/rmdir.proto

package rmdir

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	proto "yrcf_grpc_case/grpc/common/proto"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message for rpc rmdir
type RmDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseAbsolutePath bool `protobuf:"varint,1,opt,name=use_absolute_path,json=useAbsolutePath,proto3" json:"use_absolute_path,omitempty"`
	// if target directory is not empty, must set true
	RemoveRecursively bool     `protobuf:"varint,2,opt,name=remove_recursively,json=removeRecursively,proto3" json:"remove_recursively,omitempty"`
	Path              []string `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *RmDirRequest) Reset() {
	*x = RmDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rmdir_proto_rmdir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RmDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmDirRequest) ProtoMessage() {}

func (x *RmDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rmdir_proto_rmdir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmDirRequest.ProtoReflect.Descriptor instead.
func (*RmDirRequest) Descriptor() ([]byte, []int) {
	return file_rmdir_proto_rmdir_proto_rawDescGZIP(), []int{0}
}

func (x *RmDirRequest) GetUseAbsolutePath() bool {
	if x != nil {
		return x.UseAbsolutePath
	}
	return false
}

func (x *RmDirRequest) GetRemoveRecursively() bool {
	if x != nil {
		return x.RemoveRecursively
	}
	return false
}

func (x *RmDirRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

type RmDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RmDirResponse) Reset() {
	*x = RmDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rmdir_proto_rmdir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RmDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmDirResponse) ProtoMessage() {}

func (x *RmDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rmdir_proto_rmdir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmDirResponse.ProtoReflect.Descriptor instead.
func (*RmDirResponse) Descriptor() ([]byte, []int) {
	return file_rmdir_proto_rmdir_proto_rawDescGZIP(), []int{1}
}

func (x *RmDirResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_rmdir_proto_rmdir_proto protoreflect.FileDescriptor

var file_rmdir_proto_rmdir_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x6d, 0x64, 0x69, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6d,
	0x64, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x59, 0x72, 0x63, 0x66, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x0c, 0x52, 0x6d, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x5f, 0x61, 0x62, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0f, 0x75, 0x73, 0x65, 0x41, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x75, 0x72,
	0x73, 0x69, 0x76, 0x65, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x30, 0x0a, 0x0d, 0x52, 0x6d, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x45, 0x0a, 0x05, 0x52, 0x6d, 0x44, 0x69, 0x72, 0x12, 0x3c,
	0x0a, 0x05, 0x52, 0x6d, 0x44, 0x69, 0x72, 0x12, 0x17, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6d, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6d, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25,
	0x79, 0x72, 0x63, 0x66, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x73, 0x65, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x72, 0x6d, 0x64, 0x69, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x72, 0x6d, 0x64, 0x69, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rmdir_proto_rmdir_proto_rawDescOnce sync.Once
	file_rmdir_proto_rmdir_proto_rawDescData = file_rmdir_proto_rmdir_proto_rawDesc
)

func file_rmdir_proto_rmdir_proto_rawDescGZIP() []byte {
	file_rmdir_proto_rmdir_proto_rawDescOnce.Do(func() {
		file_rmdir_proto_rmdir_proto_rawDescData = protoimpl.X.CompressGZIP(file_rmdir_proto_rmdir_proto_rawDescData)
	})
	return file_rmdir_proto_rmdir_proto_rawDescData
}

var file_rmdir_proto_rmdir_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rmdir_proto_rmdir_proto_goTypes = []any{
	(*RmDirRequest)(nil),  // 0: YrcfAgent.RmDirRequest
	(*RmDirResponse)(nil), // 1: YrcfAgent.RmDirResponse
	(*proto.ResMes)(nil),  // 2: ResMes
}
var file_rmdir_proto_rmdir_proto_depIdxs = []int32{
	2, // 0: YrcfAgent.RmDirResponse.result:type_name -> ResMes
	0, // 1: YrcfAgent.RmDir.RmDir:input_type -> YrcfAgent.RmDirRequest
	1, // 2: YrcfAgent.RmDir.RmDir:output_type -> YrcfAgent.RmDirResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rmdir_proto_rmdir_proto_init() }
func file_rmdir_proto_rmdir_proto_init() {
	if File_rmdir_proto_rmdir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rmdir_proto_rmdir_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RmDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rmdir_proto_rmdir_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RmDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rmdir_proto_rmdir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rmdir_proto_rmdir_proto_goTypes,
		DependencyIndexes: file_rmdir_proto_rmdir_proto_depIdxs,
		MessageInfos:      file_rmdir_proto_rmdir_proto_msgTypes,
	}.Build()
	File_rmdir_proto_rmdir_proto = out.File
	file_rmdir_proto_rmdir_proto_rawDesc = nil
	file_rmdir_proto_rmdir_proto_goTypes = nil
	file_rmdir_proto_rmdir_proto_depIdxs = nil
}
