// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: mkfs/proto/mkfs.proto

package mkfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	proto "yrcf_grpc_case/grpc/common/proto/"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message for rpc mkfs
type MkfsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MkfsRequest) Reset() {
	*x = MkfsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mkfs_proto_mkfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MkfsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkfsRequest) ProtoMessage() {}

func (x *MkfsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mkfs_proto_mkfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkfsRequest.ProtoReflect.Descriptor instead.
func (*MkfsRequest) Descriptor() ([]byte, []int) {
	return file_mkfs_proto_mkfs_proto_rawDescGZIP(), []int{0}
}

type MkfsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MkfsResponse) Reset() {
	*x = MkfsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mkfs_proto_mkfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MkfsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkfsResponse) ProtoMessage() {}

func (x *MkfsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mkfs_proto_mkfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkfsResponse.ProtoReflect.Descriptor instead.
func (*MkfsResponse) Descriptor() ([]byte, []int) {
	return file_mkfs_proto_mkfs_proto_rawDescGZIP(), []int{1}
}

func (x *MkfsResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_mkfs_proto_mkfs_proto protoreflect.FileDescriptor

var file_mkfs_proto_mkfs_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x6b, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6b, 0x66,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x1a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x6b, 0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x39, 0x0a, 0x0c, 0x4d, 0x6b, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65,
	0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x41, 0x0a, 0x04,
	0x4d, 0x6b, 0x66, 0x73, 0x12, 0x39, 0x0a, 0x04, 0x4d, 0x6b, 0x66, 0x73, 0x12, 0x16, 0x2e, 0x59,
	0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6b, 0x66, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x4d, 0x6b, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x26, 0x5a, 0x24, 0x79, 0x72, 0x63, 0x66, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x73,
	0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x6b, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x3b, 0x6d, 0x6b, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mkfs_proto_mkfs_proto_rawDescOnce sync.Once
	file_mkfs_proto_mkfs_proto_rawDescData = file_mkfs_proto_mkfs_proto_rawDesc
)

func file_mkfs_proto_mkfs_proto_rawDescGZIP() []byte {
	file_mkfs_proto_mkfs_proto_rawDescOnce.Do(func() {
		file_mkfs_proto_mkfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_mkfs_proto_mkfs_proto_rawDescData)
	})
	return file_mkfs_proto_mkfs_proto_rawDescData
}

var file_mkfs_proto_mkfs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mkfs_proto_mkfs_proto_goTypes = []any{
	(*MkfsRequest)(nil),  // 0: YrcfAgent.MkfsRequest
	(*MkfsResponse)(nil), // 1: YrcfAgent.MkfsResponse
	(*proto.ResMes)(nil), // 2: YrcfAgent.ResMes
}
var file_mkfs_proto_mkfs_proto_depIdxs = []int32{
	2, // 0: YrcfAgent.MkfsResponse.result:type_name -> YrcfAgent.ResMes
	0, // 1: YrcfAgent.Mkfs.Mkfs:input_type -> YrcfAgent.MkfsRequest
	1, // 2: YrcfAgent.Mkfs.Mkfs:output_type -> YrcfAgent.MkfsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mkfs_proto_mkfs_proto_init() }
func file_mkfs_proto_mkfs_proto_init() {
	if File_mkfs_proto_mkfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mkfs_proto_mkfs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MkfsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mkfs_proto_mkfs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MkfsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mkfs_proto_mkfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mkfs_proto_mkfs_proto_goTypes,
		DependencyIndexes: file_mkfs_proto_mkfs_proto_depIdxs,
		MessageInfos:      file_mkfs_proto_mkfs_proto_msgTypes,
	}.Build()
	File_mkfs_proto_mkfs_proto = out.File
	file_mkfs_proto_mkfs_proto_rawDesc = nil
	file_mkfs_proto_mkfs_proto_goTypes = nil
	file_mkfs_proto_mkfs_proto_depIdxs = nil
}
