// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: mkfs/proto/mkfs.proto

package mkfs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Mkfs_Mkfs_FullMethodName = "/YrcfAgent.Mkfs/Mkfs"
)

// MkfsClient is the client API for Mkfs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MkfsClient interface {
	Mkfs(ctx context.Context, in *MkfsRequest, opts ...grpc.CallOption) (*MkfsResponse, error)
}

type mkfsClient struct {
	cc grpc.ClientConnInterface
}

func NewMkfsClient(cc grpc.ClientConnInterface) MkfsClient {
	return &mkfsClient{cc}
}

func (c *mkfsClient) Mkfs(ctx context.Context, in *MkfsRequest, opts ...grpc.CallOption) (*MkfsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkfsResponse)
	err := c.cc.Invoke(ctx, Mkfs_Mkfs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MkfsServer is the server API for Mkfs service.
// All implementations must embed UnimplementedMkfsServer
// for forward compatibility
type MkfsServer interface {
	Mkfs(context.Context, *MkfsRequest) (*MkfsResponse, error)
	mustEmbedUnimplementedMkfsServer()
}

// UnimplementedMkfsServer must be embedded to have forward compatible implementations.
type UnimplementedMkfsServer struct {
}

func (UnimplementedMkfsServer) Mkfs(context.Context, *MkfsRequest) (*MkfsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkfs not implemented")
}
func (UnimplementedMkfsServer) mustEmbedUnimplementedMkfsServer() {}

// UnsafeMkfsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MkfsServer will
// result in compilation errors.
type UnsafeMkfsServer interface {
	mustEmbedUnimplementedMkfsServer()
}

func RegisterMkfsServer(s grpc.ServiceRegistrar, srv MkfsServer) {
	s.RegisterService(&Mkfs_ServiceDesc, srv)
}

func _Mkfs_Mkfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkfsServer).Mkfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mkfs_Mkfs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkfsServer).Mkfs(ctx, req.(*MkfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mkfs_ServiceDesc is the grpc.ServiceDesc for Mkfs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mkfs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "YrcfAgent.Mkfs",
	HandlerType: (*MkfsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mkfs",
			Handler:    _Mkfs_Mkfs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mkfs/proto/mkfs.proto",
}
