// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: clientstats/proto/clientstats.proto

package clientstats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	proto "yrcf_grpc_case/grpc/common/proto"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// client_stats_type = 0, sum of external clients
// client_stats_type = 1, sum of internal and external clients
// client_stats_type = 2, sum of internal clients
type ClientStatsRequest_StatsType int32

const (
	ClientStatsRequest_EXT    ClientStatsRequest_StatsType = 0
	ClientStatsRequest_INTEXT ClientStatsRequest_StatsType = 1
	ClientStatsRequest_INT    ClientStatsRequest_StatsType = 2
)

// Enum value maps for ClientStatsRequest_StatsType.
var (
	ClientStatsRequest_StatsType_name = map[int32]string{
		0: "EXT",
		1: "INTEXT",
		2: "INT",
	}
	ClientStatsRequest_StatsType_value = map[string]int32{
		"EXT":    0,
		"INTEXT": 1,
		"INT":    2,
	}
)

func (x ClientStatsRequest_StatsType) Enum() *ClientStatsRequest_StatsType {
	p := new(ClientStatsRequest_StatsType)
	*p = x
	return p
}

func (x ClientStatsRequest_StatsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientStatsRequest_StatsType) Descriptor() protoreflect.EnumDescriptor {
	return file_clientstats_proto_clientstats_proto_enumTypes[0].Descriptor()
}

func (ClientStatsRequest_StatsType) Type() protoreflect.EnumType {
	return &file_clientstats_proto_clientstats_proto_enumTypes[0]
}

func (x ClientStatsRequest_StatsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientStatsRequest_StatsType.Descriptor instead.
func (ClientStatsRequest_StatsType) EnumDescriptor() ([]byte, []int) {
	return file_clientstats_proto_clientstats_proto_rawDescGZIP(), []int{0, 0}
}

// grpc client: get client stats
type ClientStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// true: hide server ip
	HideInternalIps bool `protobuf:"varint,2,opt,name=hide_internal_ips,json=hideInternalIps,proto3" json:"hide_internal_ips,omitempty"`
	// true: return all client even if opcounter is zero
	ReturnZeroStats bool                         `protobuf:"varint,3,opt,name=return_zero_stats,json=returnZeroStats,proto3" json:"return_zero_stats,omitempty"`
	ClientStatsType ClientStatsRequest_StatsType `protobuf:"varint,4,opt,name=client_stats_type,json=clientStatsType,proto3,enum=YrcfAgent.ClientStatsRequest_StatsType" json:"client_stats_type,omitempty"`
	Cidr            string                       `protobuf:"bytes,5,opt,name=cidr,proto3" json:"cidr,omitempty"`
}

func (x *ClientStatsRequest) Reset() {
	*x = ClientStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientstats_proto_clientstats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatsRequest) ProtoMessage() {}

func (x *ClientStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientstats_proto_clientstats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatsRequest.ProtoReflect.Descriptor instead.
func (*ClientStatsRequest) Descriptor() ([]byte, []int) {
	return file_clientstats_proto_clientstats_proto_rawDescGZIP(), []int{0}
}

func (x *ClientStatsRequest) GetHideInternalIps() bool {
	if x != nil {
		return x.HideInternalIps
	}
	return false
}

func (x *ClientStatsRequest) GetReturnZeroStats() bool {
	if x != nil {
		return x.ReturnZeroStats
	}
	return false
}

func (x *ClientStatsRequest) GetClientStatsType() ClientStatsRequest_StatsType {
	if x != nil {
		return x.ClientStatsType
	}
	return ClientStatsRequest_EXT
}

func (x *ClientStatsRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

// grpc server: return client stats
type ClientStatsRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// attention:
	// the first message is total size, the ip is fix string "total", the online is true
	// the client message start with the second message
	// client ip
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// true: client ip is online
	Online bool `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	// mds or oss opcounter
	Opcounters []uint64 `protobuf:"varint,3,rep,packed,name=opcounters,proto3" json:"opcounters,omitempty"`
}

func (x *ClientStatsRet) Reset() {
	*x = ClientStatsRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientstats_proto_clientstats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStatsRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatsRet) ProtoMessage() {}

func (x *ClientStatsRet) ProtoReflect() protoreflect.Message {
	mi := &file_clientstats_proto_clientstats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatsRet.ProtoReflect.Descriptor instead.
func (*ClientStatsRet) Descriptor() ([]byte, []int) {
	return file_clientstats_proto_clientstats_proto_rawDescGZIP(), []int{1}
}

func (x *ClientStatsRet) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClientStatsRet) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *ClientStatsRet) GetOpcounters() []uint64 {
	if x != nil {
		return x.Opcounters
	}
	return nil
}

type ClientStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Value  []*ClientStatsRet `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *ClientStatsResponse) Reset() {
	*x = ClientStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientstats_proto_clientstats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatsResponse) ProtoMessage() {}

func (x *ClientStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientstats_proto_clientstats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatsResponse.ProtoReflect.Descriptor instead.
func (*ClientStatsResponse) Descriptor() ([]byte, []int) {
	return file_clientstats_proto_clientstats_proto_rawDescGZIP(), []int{2}
}

func (x *ClientStatsResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ClientStatsResponse) GetValue() []*ClientStatsRet {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_clientstats_proto_clientstats_proto protoreflect.FileDescriptor

var file_clientstats_proto_clientstats_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x1a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x80, 0x02, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x69, 0x64, 0x65, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x68, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x49, 0x70, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x7a, 0x65,
	0x72, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f,
	0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5a, 0x65, 0x72, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x53, 0x0a, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x59, 0x72, 0x63,
	0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x72, 0x22, 0x29, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x49, 0x4e, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e,
	0x54, 0x10, 0x02, 0x22, 0x58, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6f, 0x70, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x0a, 0x6f, 0x70, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22, 0x67, 0x0a,
	0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x74, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xa7, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x4b, 0x0a, 0x08, 0x4d, 0x64, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x1d, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x08, 0x4f, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x1d, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x33, 0x5a, 0x31, 0x79, 0x72, 0x63, 0x66, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61,
	0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientstats_proto_clientstats_proto_rawDescOnce sync.Once
	file_clientstats_proto_clientstats_proto_rawDescData = file_clientstats_proto_clientstats_proto_rawDesc
)

func file_clientstats_proto_clientstats_proto_rawDescGZIP() []byte {
	file_clientstats_proto_clientstats_proto_rawDescOnce.Do(func() {
		file_clientstats_proto_clientstats_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientstats_proto_clientstats_proto_rawDescData)
	})
	return file_clientstats_proto_clientstats_proto_rawDescData
}

var file_clientstats_proto_clientstats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clientstats_proto_clientstats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clientstats_proto_clientstats_proto_goTypes = []any{
	(ClientStatsRequest_StatsType)(0), // 0: YrcfAgent.ClientStatsRequest.StatsType
	(*ClientStatsRequest)(nil),        // 1: YrcfAgent.ClientStatsRequest
	(*ClientStatsRet)(nil),            // 2: YrcfAgent.ClientStatsRet
	(*ClientStatsResponse)(nil),       // 3: YrcfAgent.ClientStatsResponse
	(*proto.ResMes)(nil),              // 4: ResMes
}
var file_clientstats_proto_clientstats_proto_depIdxs = []int32{
	0, // 0: YrcfAgent.ClientStatsRequest.client_stats_type:type_name -> YrcfAgent.ClientStatsRequest.StatsType
	4, // 1: YrcfAgent.ClientStatsResponse.result:type_name -> ResMes
	2, // 2: YrcfAgent.ClientStatsResponse.value:type_name -> YrcfAgent.ClientStatsRet
	1, // 3: YrcfAgent.ClientStats.MdsStats:input_type -> YrcfAgent.ClientStatsRequest
	1, // 4: YrcfAgent.ClientStats.OssStats:input_type -> YrcfAgent.ClientStatsRequest
	3, // 5: YrcfAgent.ClientStats.MdsStats:output_type -> YrcfAgent.ClientStatsResponse
	3, // 6: YrcfAgent.ClientStats.OssStats:output_type -> YrcfAgent.ClientStatsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_clientstats_proto_clientstats_proto_init() }
func file_clientstats_proto_clientstats_proto_init() {
	if File_clientstats_proto_clientstats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientstats_proto_clientstats_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ClientStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientstats_proto_clientstats_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ClientStatsRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientstats_proto_clientstats_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ClientStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientstats_proto_clientstats_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientstats_proto_clientstats_proto_goTypes,
		DependencyIndexes: file_clientstats_proto_clientstats_proto_depIdxs,
		EnumInfos:         file_clientstats_proto_clientstats_proto_enumTypes,
		MessageInfos:      file_clientstats_proto_clientstats_proto_msgTypes,
	}.Build()
	File_clientstats_proto_clientstats_proto = out.File
	file_clientstats_proto_clientstats_proto_rawDesc = nil
	file_clientstats_proto_clientstats_proto_goTypes = nil
	file_clientstats_proto_clientstats_proto_depIdxs = nil
}
