// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: mkdir/proto/mkdir.proto

package mkdir

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MkDir_MkDir_FullMethodName = "/YrcfAgent.MkDir/MkDir"
)

// MkDirClient is the client API for MkDir service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MkDirClient interface {
	MkDir(ctx context.Context, in *MkDirRequest, opts ...grpc.CallOption) (*MkDirResponse, error)
}

type mkDirClient struct {
	cc grpc.ClientConnInterface
}

func NewMkDirClient(cc grpc.ClientConnInterface) MkDirClient {
	return &mkDirClient{cc}
}

func (c *mkDirClient) MkDir(ctx context.Context, in *MkDirRequest, opts ...grpc.CallOption) (*MkDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkDirResponse)
	err := c.cc.Invoke(ctx, MkDir_MkDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MkDirServer is the server API for MkDir service.
// All implementations must embed UnimplementedMkDirServer
// for forward compatibility
type MkDirServer interface {
	MkDir(context.Context, *MkDirRequest) (*MkDirResponse, error)
	mustEmbedUnimplementedMkDirServer()
}

// UnimplementedMkDirServer must be embedded to have forward compatible implementations.
type UnimplementedMkDirServer struct {
}

func (UnimplementedMkDirServer) MkDir(context.Context, *MkDirRequest) (*MkDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MkDir not implemented")
}
func (UnimplementedMkDirServer) mustEmbedUnimplementedMkDirServer() {}

// UnsafeMkDirServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MkDirServer will
// result in compilation errors.
type UnsafeMkDirServer interface {
	mustEmbedUnimplementedMkDirServer()
}

func RegisterMkDirServer(s grpc.ServiceRegistrar, srv MkDirServer) {
	s.RegisterService(&MkDir_ServiceDesc, srv)
}

func _MkDir_MkDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkDirServer).MkDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MkDir_MkDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkDirServer).MkDir(ctx, req.(*MkDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MkDir_ServiceDesc is the grpc.ServiceDesc for MkDir service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MkDir_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "YrcfAgent.MkDir",
	HandlerType: (*MkDirServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MkDir",
			Handler:    _MkDir_MkDir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mkdir/proto/mkdir.proto",
}
