// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: listosds/proto/listosds.proto

package listosds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	proto "yrcf_grpc_case/grpc/common/proto/"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OsdInfo_OsdType int32

const (
	OsdInfo_OSS OsdInfo_OsdType = 0
	OsdInfo_MDS OsdInfo_OsdType = 1
)

// Enum value maps for OsdInfo_OsdType.
var (
	OsdInfo_OsdType_name = map[int32]string{
		0: "OSS",
		1: "MDS",
	}
	OsdInfo_OsdType_value = map[string]int32{
		"OSS": 0,
		"MDS": 1,
	}
)

func (x OsdInfo_OsdType) Enum() *OsdInfo_OsdType {
	p := new(OsdInfo_OsdType)
	*p = x
	return p
}

func (x OsdInfo_OsdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OsdInfo_OsdType) Descriptor() protoreflect.EnumDescriptor {
	return file_listosds_proto_listosds_proto_enumTypes[0].Descriptor()
}

func (OsdInfo_OsdType) Type() protoreflect.EnumType {
	return &file_listosds_proto_listosds_proto_enumTypes[0]
}

func (x OsdInfo_OsdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OsdInfo_OsdType.Descriptor instead.
func (OsdInfo_OsdType) EnumDescriptor() ([]byte, []int) {
	return file_listosds_proto_listosds_proto_rawDescGZIP(), []int{0, 0}
}

type OsdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OsdType   OsdInfo_OsdType `protobuf:"varint,1,opt,name=osd_type,json=osdType,proto3,enum=YrcfAgent.OsdInfo_OsdType" json:"osd_type,omitempty"`
	OsdId     uint32          `protobuf:"varint,2,opt,name=osd_id,json=osdId,proto3" json:"osd_id,omitempty"`
	NodeName  string          `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeId    string          `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GroupInfo string          `protobuf:"bytes,5,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	RoleInfo  string          `protobuf:"bytes,6,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
	StateStr  string          `protobuf:"bytes,7,opt,name=state_str,json=stateStr,proto3" json:"state_str,omitempty"`
	PoolName  string          `protobuf:"bytes,8,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	SpaceInfo string          `protobuf:"bytes,9,opt,name=space_info,json=spaceInfo,proto3" json:"space_info,omitempty"`
	PoolInfo  string          `protobuf:"bytes,10,opt,name=pool_info,json=poolInfo,proto3" json:"pool_info,omitempty"`
}

func (x *OsdInfo) Reset() {
	*x = OsdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listosds_proto_listosds_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OsdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsdInfo) ProtoMessage() {}

func (x *OsdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_listosds_proto_listosds_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsdInfo.ProtoReflect.Descriptor instead.
func (*OsdInfo) Descriptor() ([]byte, []int) {
	return file_listosds_proto_listosds_proto_rawDescGZIP(), []int{0}
}

func (x *OsdInfo) GetOsdType() OsdInfo_OsdType {
	if x != nil {
		return x.OsdType
	}
	return OsdInfo_OSS
}

func (x *OsdInfo) GetOsdId() uint32 {
	if x != nil {
		return x.OsdId
	}
	return 0
}

func (x *OsdInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *OsdInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *OsdInfo) GetGroupInfo() string {
	if x != nil {
		return x.GroupInfo
	}
	return ""
}

func (x *OsdInfo) GetRoleInfo() string {
	if x != nil {
		return x.RoleInfo
	}
	return ""
}

func (x *OsdInfo) GetStateStr() string {
	if x != nil {
		return x.StateStr
	}
	return ""
}

func (x *OsdInfo) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *OsdInfo) GetSpaceInfo() string {
	if x != nil {
		return x.SpaceInfo
	}
	return ""
}

func (x *OsdInfo) GetPoolInfo() string {
	if x != nil {
		return x.PoolInfo
	}
	return ""
}

// message for rpc list osd
type ListOsdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OsdType OsdInfo_OsdType `protobuf:"varint,1,opt,name=osd_type,json=osdType,proto3,enum=YrcfAgent.OsdInfo_OsdType" json:"osd_type,omitempty"`
	PoolId  string          `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (x *ListOsdsRequest) Reset() {
	*x = ListOsdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listosds_proto_listosds_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOsdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOsdsRequest) ProtoMessage() {}

func (x *ListOsdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listosds_proto_listosds_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOsdsRequest.ProtoReflect.Descriptor instead.
func (*ListOsdsRequest) Descriptor() ([]byte, []int) {
	return file_listosds_proto_listosds_proto_rawDescGZIP(), []int{1}
}

func (x *ListOsdsRequest) GetOsdType() OsdInfo_OsdType {
	if x != nil {
		return x.OsdType
	}
	return OsdInfo_OSS
}

func (x *ListOsdsRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type ListOsdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	OsdInfoList []*OsdInfo    `protobuf:"bytes,2,rep,name=osd_info_list,json=osdInfoList,proto3" json:"osd_info_list,omitempty"`
}

func (x *ListOsdsResponse) Reset() {
	*x = ListOsdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listosds_proto_listosds_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOsdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOsdsResponse) ProtoMessage() {}

func (x *ListOsdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listosds_proto_listosds_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOsdsResponse.ProtoReflect.Descriptor instead.
func (*ListOsdsResponse) Descriptor() ([]byte, []int) {
	return file_listosds_proto_listosds_proto_rawDescGZIP(), []int{2}
}

func (x *ListOsdsResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListOsdsResponse) GetOsdInfoList() []*OsdInfo {
	if x != nil {
		return x.OsdInfoList
	}
	return nil
}

var File_listosds_proto_listosds_proto protoreflect.FileDescriptor

var file_listosds_proto_listosds_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x73, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x73, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x02, 0x0a, 0x07, 0x4f,
	0x73, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x08, 0x6f, 0x73, 0x64, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x73, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4f, 0x73, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6f, 0x73, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x6f, 0x73, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f,
	0x73, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x73, 0x74, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1b, 0x0a, 0x07,
	0x4f, 0x73, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x53, 0x53, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x4d, 0x44, 0x53, 0x10, 0x01, 0x22, 0x61, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x73, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08,
	0x6f, 0x73, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x73, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x4f, 0x73, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6f, 0x73, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x73, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x4d, 0x65, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x6f,
	0x73, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4f,
	0x73, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6f, 0x73, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x32, 0x51, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x73, 0x64, 0x73, 0x12,
	0x45, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x73, 0x64, 0x73, 0x12, 0x1a, 0x2e, 0x59, 0x72,
	0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x73, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x73, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x79, 0x72, 0x63, 0x66, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x69,
	0x73, 0x74, 0x6f, 0x73, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x3b, 0x6c, 0x69,
	0x73, 0x74, 0x6f, 0x73, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listosds_proto_listosds_proto_rawDescOnce sync.Once
	file_listosds_proto_listosds_proto_rawDescData = file_listosds_proto_listosds_proto_rawDesc
)

func file_listosds_proto_listosds_proto_rawDescGZIP() []byte {
	file_listosds_proto_listosds_proto_rawDescOnce.Do(func() {
		file_listosds_proto_listosds_proto_rawDescData = protoimpl.X.CompressGZIP(file_listosds_proto_listosds_proto_rawDescData)
	})
	return file_listosds_proto_listosds_proto_rawDescData
}

var file_listosds_proto_listosds_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_listosds_proto_listosds_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_listosds_proto_listosds_proto_goTypes = []any{
	(OsdInfo_OsdType)(0),     // 0: YrcfAgent.OsdInfo.OsdType
	(*OsdInfo)(nil),          // 1: YrcfAgent.OsdInfo
	(*ListOsdsRequest)(nil),  // 2: YrcfAgent.ListOsdsRequest
	(*ListOsdsResponse)(nil), // 3: YrcfAgent.ListOsdsResponse
	(*proto.ResMes)(nil),     // 4: YrcfAgent.ResMes
}
var file_listosds_proto_listosds_proto_depIdxs = []int32{
	0, // 0: YrcfAgent.OsdInfo.osd_type:type_name -> YrcfAgent.OsdInfo.OsdType
	0, // 1: YrcfAgent.ListOsdsRequest.osd_type:type_name -> YrcfAgent.OsdInfo.OsdType
	4, // 2: YrcfAgent.ListOsdsResponse.result:type_name -> YrcfAgent.ResMes
	1, // 3: YrcfAgent.ListOsdsResponse.osd_info_list:type_name -> YrcfAgent.OsdInfo
	2, // 4: YrcfAgent.ListOsds.ListOsds:input_type -> YrcfAgent.ListOsdsRequest
	3, // 5: YrcfAgent.ListOsds.ListOsds:output_type -> YrcfAgent.ListOsdsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_listosds_proto_listosds_proto_init() }
func file_listosds_proto_listosds_proto_init() {
	if File_listosds_proto_listosds_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_listosds_proto_listosds_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OsdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listosds_proto_listosds_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListOsdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listosds_proto_listosds_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListOsdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listosds_proto_listosds_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listosds_proto_listosds_proto_goTypes,
		DependencyIndexes: file_listosds_proto_listosds_proto_depIdxs,
		EnumInfos:         file_listosds_proto_listosds_proto_enumTypes,
		MessageInfos:      file_listosds_proto_listosds_proto_msgTypes,
	}.Build()
	File_listosds_proto_listosds_proto = out.File
	file_listosds_proto_listosds_proto_rawDesc = nil
	file_listosds_proto_listosds_proto_goTypes = nil
	file_listosds_proto_listosds_proto_depIdxs = nil
}
