// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: listosds/proto/listosds.proto

package listosds

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ListOsds_ListOsds_FullMethodName = "/YrcfAgent.ListOsds/ListOsds"
)

// ListOsdsClient is the client API for ListOsds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListOsdsClient interface {
	ListOsds(ctx context.Context, in *ListOsdsRequest, opts ...grpc.CallOption) (*ListOsdsResponse, error)
}

type listOsdsClient struct {
	cc grpc.ClientConnInterface
}

func NewListOsdsClient(cc grpc.ClientConnInterface) ListOsdsClient {
	return &listOsdsClient{cc}
}

func (c *listOsdsClient) ListOsds(ctx context.Context, in *ListOsdsRequest, opts ...grpc.CallOption) (*ListOsdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOsdsResponse)
	err := c.cc.Invoke(ctx, ListOsds_ListOsds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListOsdsServer is the server API for ListOsds service.
// All implementations must embed UnimplementedListOsdsServer
// for forward compatibility
type ListOsdsServer interface {
	ListOsds(context.Context, *ListOsdsRequest) (*ListOsdsResponse, error)
	mustEmbedUnimplementedListOsdsServer()
}

// UnimplementedListOsdsServer must be embedded to have forward compatible implementations.
type UnimplementedListOsdsServer struct {
}

func (UnimplementedListOsdsServer) ListOsds(context.Context, *ListOsdsRequest) (*ListOsdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOsds not implemented")
}
func (UnimplementedListOsdsServer) mustEmbedUnimplementedListOsdsServer() {}

// UnsafeListOsdsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListOsdsServer will
// result in compilation errors.
type UnsafeListOsdsServer interface {
	mustEmbedUnimplementedListOsdsServer()
}

func RegisterListOsdsServer(s grpc.ServiceRegistrar, srv ListOsdsServer) {
	s.RegisterService(&ListOsds_ServiceDesc, srv)
}

func _ListOsds_ListOsds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOsdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListOsdsServer).ListOsds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListOsds_ListOsds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListOsdsServer).ListOsds(ctx, req.(*ListOsdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ListOsds_ServiceDesc is the grpc.ServiceDesc for ListOsds service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListOsds_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "YrcfAgent.ListOsds",
	HandlerType: (*ListOsdsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOsds",
			Handler:    _ListOsds_ListOsds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "listosds/proto/listosds.proto",
}
