// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: mdsoverview/proto/mdsoverview.proto

package mdsoverview

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MdsOverview_MdsOverview_FullMethodName = "/YrcfAgent.MdsOverview/MdsOverview"
)

// MdsOverviewClient is the client API for MdsOverview service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MdsOverviewClient interface {
	MdsOverview(ctx context.Context, in *MdsOverviewRequest, opts ...grpc.CallOption) (*MdsOverviewResponse, error)
}

type mdsOverviewClient struct {
	cc grpc.ClientConnInterface
}

func NewMdsOverviewClient(cc grpc.ClientConnInterface) MdsOverviewClient {
	return &mdsOverviewClient{cc}
}

func (c *mdsOverviewClient) MdsOverview(ctx context.Context, in *MdsOverviewRequest, opts ...grpc.CallOption) (*MdsOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MdsOverviewResponse)
	err := c.cc.Invoke(ctx, MdsOverview_MdsOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MdsOverviewServer is the server API for MdsOverview service.
// All implementations must embed UnimplementedMdsOverviewServer
// for forward compatibility
type MdsOverviewServer interface {
	MdsOverview(context.Context, *MdsOverviewRequest) (*MdsOverviewResponse, error)
	mustEmbedUnimplementedMdsOverviewServer()
}

// UnimplementedMdsOverviewServer must be embedded to have forward compatible implementations.
type UnimplementedMdsOverviewServer struct {
}

func (UnimplementedMdsOverviewServer) MdsOverview(context.Context, *MdsOverviewRequest) (*MdsOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MdsOverview not implemented")
}
func (UnimplementedMdsOverviewServer) mustEmbedUnimplementedMdsOverviewServer() {}

// UnsafeMdsOverviewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MdsOverviewServer will
// result in compilation errors.
type UnsafeMdsOverviewServer interface {
	mustEmbedUnimplementedMdsOverviewServer()
}

func RegisterMdsOverviewServer(s grpc.ServiceRegistrar, srv MdsOverviewServer) {
	s.RegisterService(&MdsOverview_ServiceDesc, srv)
}

func _MdsOverview_MdsOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MdsOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdsOverviewServer).MdsOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdsOverview_MdsOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdsOverviewServer).MdsOverview(ctx, req.(*MdsOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MdsOverview_ServiceDesc is the grpc.ServiceDesc for MdsOverview service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MdsOverview_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "YrcfAgent.MdsOverview",
	HandlerType: (*MdsOverviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MdsOverview",
			Handler:    _MdsOverview_MdsOverview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mdsoverview/proto/mdsoverview.proto",
}
