//
//  This proto is used for setting log level in corresponding agent,
//  thus it is a developer tool while debugging.
//  Be noted, do not integrate this proto into your system for it may
//  be deleted in the future.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: setloglevel/proto/setloglevel.proto

package setloglevel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	proto "yrcf_grpc_case/grpc/common/proto/"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetLogLevelRequest_LogLevel int32

const (
	SetLogLevelRequest_FATAL SetLogLevelRequest_LogLevel = 0
	SetLogLevelRequest_ERR   SetLogLevelRequest_LogLevel = 1
	SetLogLevelRequest_WARN  SetLogLevelRequest_LogLevel = 2
	SetLogLevelRequest_INFO  SetLogLevelRequest_LogLevel = 3
	SetLogLevelRequest_DBG   SetLogLevelRequest_LogLevel = 4
	SetLogLevelRequest_TRACE SetLogLevelRequest_LogLevel = 5
)

// Enum value maps for SetLogLevelRequest_LogLevel.
var (
	SetLogLevelRequest_LogLevel_name = map[int32]string{
		0: "FATAL",
		1: "ERR",
		2: "WARN",
		3: "INFO",
		4: "DBG",
		5: "TRACE",
	}
	SetLogLevelRequest_LogLevel_value = map[string]int32{
		"FATAL": 0,
		"ERR":   1,
		"WARN":  2,
		"INFO":  3,
		"DBG":   4,
		"TRACE": 5,
	}
)

func (x SetLogLevelRequest_LogLevel) Enum() *SetLogLevelRequest_LogLevel {
	p := new(SetLogLevelRequest_LogLevel)
	*p = x
	return p
}

func (x SetLogLevelRequest_LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetLogLevelRequest_LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_setloglevel_proto_setloglevel_proto_enumTypes[0].Descriptor()
}

func (SetLogLevelRequest_LogLevel) Type() protoreflect.EnumType {
	return &file_setloglevel_proto_setloglevel_proto_enumTypes[0]
}

func (x SetLogLevelRequest_LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetLogLevelRequest_LogLevel.Descriptor instead.
func (SetLogLevelRequest_LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_setloglevel_proto_setloglevel_proto_rawDescGZIP(), []int{0, 0}
}

// message for set log level
type SetLogLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogLevel SetLogLevelRequest_LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=YrcfAgent.SetLogLevelRequest_LogLevel" json:"log_level,omitempty"`
}

func (x *SetLogLevelRequest) Reset() {
	*x = SetLogLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setloglevel_proto_setloglevel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelRequest) ProtoMessage() {}

func (x *SetLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setloglevel_proto_setloglevel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelRequest.ProtoReflect.Descriptor instead.
func (*SetLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_setloglevel_proto_setloglevel_proto_rawDescGZIP(), []int{0}
}

func (x *SetLogLevelRequest) GetLogLevel() SetLogLevelRequest_LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return SetLogLevelRequest_FATAL
}

type SetLogLevelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *proto.ResMes `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetLogLevelResponse) Reset() {
	*x = SetLogLevelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setloglevel_proto_setloglevel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLogLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelResponse) ProtoMessage() {}

func (x *SetLogLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setloglevel_proto_setloglevel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelResponse.ProtoReflect.Descriptor instead.
func (*SetLogLevelResponse) Descriptor() ([]byte, []int) {
	return file_setloglevel_proto_setloglevel_proto_rawDescGZIP(), []int{1}
}

func (x *SetLogLevelResponse) GetResult() *proto.ResMes {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_setloglevel_proto_setloglevel_proto protoreflect.FileDescriptor

var file_setloglevel_proto_setloglevel_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x74, 0x6c, 0x6f, 0x67, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x74, 0x6c, 0x6f, 0x67, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x1a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa1, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x59, 0x72, 0x63,
	0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x46, 0x0a, 0x08,
	0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41, 0x54, 0x41,
	0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x52, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x57, 0x41, 0x52, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x44, 0x42, 0x47, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x52, 0x41,
	0x43, 0x45, 0x10, 0x05, 0x22, 0x40, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x59, 0x72,
	0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x5b, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x4c, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x59, 0x72, 0x63, 0x66, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x79, 0x72, 0x63, 0x66, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x63, 0x61, 0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x74, 0x6c, 0x6f,
	0x67, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x3b, 0x73, 0x65,
	0x74, 0x6c, 0x6f, 0x67, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_setloglevel_proto_setloglevel_proto_rawDescOnce sync.Once
	file_setloglevel_proto_setloglevel_proto_rawDescData = file_setloglevel_proto_setloglevel_proto_rawDesc
)

func file_setloglevel_proto_setloglevel_proto_rawDescGZIP() []byte {
	file_setloglevel_proto_setloglevel_proto_rawDescOnce.Do(func() {
		file_setloglevel_proto_setloglevel_proto_rawDescData = protoimpl.X.CompressGZIP(file_setloglevel_proto_setloglevel_proto_rawDescData)
	})
	return file_setloglevel_proto_setloglevel_proto_rawDescData
}

var file_setloglevel_proto_setloglevel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_setloglevel_proto_setloglevel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_setloglevel_proto_setloglevel_proto_goTypes = []any{
	(SetLogLevelRequest_LogLevel)(0), // 0: YrcfAgent.SetLogLevelRequest.LogLevel
	(*SetLogLevelRequest)(nil),       // 1: YrcfAgent.SetLogLevelRequest
	(*SetLogLevelResponse)(nil),      // 2: YrcfAgent.SetLogLevelResponse
	(*proto.ResMes)(nil),             // 3: YrcfAgent.ResMes
}
var file_setloglevel_proto_setloglevel_proto_depIdxs = []int32{
	0, // 0: YrcfAgent.SetLogLevelRequest.log_level:type_name -> YrcfAgent.SetLogLevelRequest.LogLevel
	3, // 1: YrcfAgent.SetLogLevelResponse.result:type_name -> YrcfAgent.ResMes
	1, // 2: YrcfAgent.SetLogLevel.SetLogLevel:input_type -> YrcfAgent.SetLogLevelRequest
	2, // 3: YrcfAgent.SetLogLevel.SetLogLevel:output_type -> YrcfAgent.SetLogLevelResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_setloglevel_proto_setloglevel_proto_init() }
func file_setloglevel_proto_setloglevel_proto_init() {
	if File_setloglevel_proto_setloglevel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_setloglevel_proto_setloglevel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SetLogLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setloglevel_proto_setloglevel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetLogLevelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_setloglevel_proto_setloglevel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_setloglevel_proto_setloglevel_proto_goTypes,
		DependencyIndexes: file_setloglevel_proto_setloglevel_proto_depIdxs,
		EnumInfos:         file_setloglevel_proto_setloglevel_proto_enumTypes,
		MessageInfos:      file_setloglevel_proto_setloglevel_proto_msgTypes,
	}.Build()
	File_setloglevel_proto_setloglevel_proto = out.File
	file_setloglevel_proto_setloglevel_proto_rawDesc = nil
	file_setloglevel_proto_setloglevel_proto_goTypes = nil
	file_setloglevel_proto_setloglevel_proto_depIdxs = nil
}
