// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: setattr/proto/setattr.proto

package setattr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SetAttr_SetAttr_FullMethodName = "/YrcfAgent.SetAttr/SetAttr"
)

// SetAttrClient is the client API for SetAttr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetAttrClient interface {
	SetAttr(ctx context.Context, in *SetAttrRequest, opts ...grpc.CallOption) (*SetAttrResponse, error)
}

type setAttrClient struct {
	cc grpc.ClientConnInterface
}

func NewSetAttrClient(cc grpc.ClientConnInterface) SetAttrClient {
	return &setAttrClient{cc}
}

func (c *setAttrClient) SetAttr(ctx context.Context, in *SetAttrRequest, opts ...grpc.CallOption) (*SetAttrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAttrResponse)
	err := c.cc.Invoke(ctx, SetAttr_SetAttr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetAttrServer is the server API for SetAttr service.
// All implementations must embed UnimplementedSetAttrServer
// for forward compatibility
type SetAttrServer interface {
	SetAttr(context.Context, *SetAttrRequest) (*SetAttrResponse, error)
	mustEmbedUnimplementedSetAttrServer()
}

// UnimplementedSetAttrServer must be embedded to have forward compatible implementations.
type UnimplementedSetAttrServer struct {
}

func (UnimplementedSetAttrServer) SetAttr(context.Context, *SetAttrRequest) (*SetAttrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAttr not implemented")
}
func (UnimplementedSetAttrServer) mustEmbedUnimplementedSetAttrServer() {}

// UnsafeSetAttrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetAttrServer will
// result in compilation errors.
type UnsafeSetAttrServer interface {
	mustEmbedUnimplementedSetAttrServer()
}

func RegisterSetAttrServer(s grpc.ServiceRegistrar, srv SetAttrServer) {
	s.RegisterService(&SetAttr_ServiceDesc, srv)
}

func _SetAttr_SetAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetAttrServer).SetAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetAttr_SetAttr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetAttrServer).SetAttr(ctx, req.(*SetAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SetAttr_ServiceDesc is the grpc.ServiceDesc for SetAttr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetAttr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "YrcfAgent.SetAttr",
	HandlerType: (*SetAttrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAttr",
			Handler:    _SetAttr_SetAttr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "setattr/proto/setattr.proto",
}
